CREATE DATABASE IF NOT EXISTS credifama_db
CHARACTER SET utf8mb4;

USE credifama_db;

CREATE TABLE IF NOT EXISTS usuarios
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    telefono VARCHAR(9) UNIQUE,
    fecha_ingresado TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);